# Generated by Django 4.0.3 on 2023-03-21 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='user',
            name='detail_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
