# Generated by Django 4.0.3 on 2023-03-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
    ]
