# Generated by Django 4.0.3 on 2023-03-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20230322_1107'),
    ]

    operations = [
    ]
